### PR TITLE
add edit button

### PR DESCRIPTION
**Pull request by MonicaG**
Updated the mkdocs yaml file to include the edit and issue buttons. This will allow a user to create a GitHub issue or PR for the given page.

I also removed the mermaid plugin as a plugin is used now instead on the devhub side to render mermaid diagrams

### CODE REVIEW

**Comment by MonicaG** [comment]
Hi! Just following up on this PR. Is it ok to merge? Thank you!

**Comment by WalterMoar** [comment]
> Hi! Just following up on this PR. Is it ok to merge? Thank you!

@vijaivir, @bhuvan-aot - thoughts on this? I'm not sure what it does :D

**Comment by MonicaG** [comment]
@WalterMoar - the change adds an edit/issue button to the documentation pages. The [Onboarding to application monitoring with Sysdig](https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/app-monitoring/sysdig-monitor-onboarding/) page has an example of it. Next to the title on the page, there is an icon of a page with a pencil. Clicking it will let a user open a PR or Issue on the repo. This lets users provide suggested edits to the page.

This PR is to add that functionality. Each page of this documentation would have that button.

**Comment by MonicaG** [comment]
@vijaivir, @bhuvan-aot @WalterMoar - is it ok for this PR to be merged?

**Comment by MonicaG** [comment]
[bhuvan-aot](https://github.com/bhuvan-aot) - thank you for the approval. Do you have a timeline on when this PR will be merged?

Thanks!

**Pull request merged**
